# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Install spin cli
        run: |
          curl -LO https://storage.googleapis.com/spinnaker-artifacts/spin/$(curl -s https://storage.googleapis.com/spinnaker-artifacts/spin/latest)/linux/amd64/spin
          chmod +x spin
          sudo mv spin /usr/local/bin/spin

      # Runs a set of commands using the runners shell
      - name: Export config spin
        run: |
          mkdir ~/.spin/
          echo "${{ secrets.CONFIG_SPIN }}" | tr -d '\r' > ~/.spin/config

      - name: Update pipeline
        run: |
          export NAME_VAR=${{ steps.vars.outputs.sha_short }}
          envsubst < pipeline.json > output.json
          spin pipeline save --file output.json

      - name: Start pipeline
        run: |
          spin pipeline execute --name nginxdeploy --application nginx1
